### ISSUE TITLE
No features listed when installed

### ISSUE THREAD

**Issue by 3nt3** [SeniorMars/tree-sitter-typst#5]
When I install this parser and run `:checkhealth nvim-treesitter` in neovim, it shows up but in the table has neither highlight, locals, folds, indents or injections.

Am I missing something?

```lua
local parser_configs = require('nvim-treesitter.parsers').get_parser_configs()
parser_configs.typst = {
  install_info = {
    url = "https://github.com/SeniorMars/tree-sitter-typst",
    files = { "src/parser.c", "src/scanner.c" },
    branch = "main"
  },
  filetype = "typst",
}
```

I am aware this could be a neovim/treesitter specific issue not concerning this project

**Comment by classabbyamp** [comment]
there are no queries for this yet so nvim-treesitter can't know what it can do

**Comment by 3nt3** [comment]
that explains it lol
